### ISSUE TITLE
Avoid using Popen with shell=True

### ISSUE THREAD

**Issue by arthaud** [reiven/tomber#6]
Hi,

You should use Popen by giving it a list of arguments instead of a single string:
```python
# good
Popen(['tomb', 'slam'])

# bad, see the warning at https://docs.python.org/2/library/subprocess.html#index-2
Popen('tomb slam', shell=True)
```
This way you will avoid security issues and you wont need functions like ``sanitize_passphrase`` and the use of ```' '.join()```

Best regards.

**Comment by reiven** [comment]
Ok @arthaud i'll try it.
:+1:  for including the documentation link
