### ISSUE TITLE
Tomb option --unsecure-dev-mode invalid: has changed to --unsafe (?)

### ISSUE THREAD

**Issue by sptankard** [reiven/tomber#7]
It seems like the tomb option `--unsecure-dev-mode` has been changed to `--unsafe` in recent versions. (Or they're are different options altogether?)

In any case, `--unsecure-dev-mode` is not a valid option for the `forge` command in Tomb v2.2.

This is blocking some basic Tomber functionality such as the `tforge` function.

Not sure if this is exactly what is going on here, but I suspect replacing all instances of `--unsecure-dev-mode` with `--unsafe` in Tomber would resolve this. But would definitely break backwards compatibility. Again, not sure what versions of Tomb are in play here.

**Comment by reiven** [comment]
Thanks @sptankard i'll take a look at this change in Tomb and update the code.

**Comment by reiven** [comment]
Thanks @sptankard , i've updated the lib so now its working with Tomb v2.2 in a4ec9a082f793071b840d20ebc47cb84860cab18
